### PR TITLE
Allow image drawing in subscreen areas

### PR DESCRIPTION
**Pull request by Johennes**
This extends the `image` method with two additional arguments for the
image origin on the screen. The previous exact size check was adapted
to ensure that the image drawn at the supplied origin does not exceed
the display dimensions.

The changes allow to update a smaller part of the screen with an
image which is especially benefitial on lower end hardware. Some
example test results from a Rasberry Pi Zero:

- Draw fullscreen image (240x320): ~0.3s
- Draw half-screen image (240x160): ~0.2s
- Draw single line of text (240x22): ~0.06s

Fixes: #48

Note that this was based off of my changes in #47 and will have to be rebased before merging.

### CODE REVIEW

**Comment by makermelissa** [comment]
As a note to reviewers, it appears this PR is dependent on #47 being approved, so I'll grab this after I have a chance to review #47.

**Comment by makermelissa** [comment]
@Johennes #47 was merged. Do you want to go ahead and rebase? Thanks

**Comment by Johennes** [comment]
👌 Will take care of it after work today.

**Comment by makermelissa** [comment]
Sounds good. Thanks!

**Comment by Johennes** [comment]
Ok, it's rebased on `master` now.

**Comment by makermelissa** [comment]
Awesome! Thank you.

**Pull request merged**
