### PR TITLE
make numpy speed improvements more prominent

### PR DESCRIPTION
**Pull request by philippkeller**
Following up on [ladyadas comment](https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display/issues/61#issuecomment-573388331) I tried to make numpy's speed improvement more prominent.

That's how I approach that. Of course this could be solved in other ways, some alternatives I considered:

- output a warning on stderr when numpy can't be imported (at top of `rgb.py`), but this is annoying for anyone who wants to run without numpy
- explicitly require numpy, remove code in `image()` that handles when numpy is not there. I didn't dare to do this but might be the most straightforward way. But there might be situations for users where they don't want numpy as it's probably quite heavy to install.
- not adding numpy to `requirements.txt`, but I think it's best to lead users to the usually best way to roll

### CODE REVIEW

**Comment by ladyada** [comment]
hi - please dont do it this way - have the gif loader example import numpy, that will force it to be installed :)

**Comment by philippkeller** [comment]
> hi - please dont do it this way - have the gif loader example import numpy, that will force it to be installed :)

I'm confused. So you mean add `import numpy` in the first line of the `image()` method? And then also remove the code which handles the case when numpy is not available?

**Comment by ladyada** [comment]
no to the gif loader example, the python script

**Comment by philippkeller** [comment]
oh, I was totally on another track :-) the thread was referring the gif example. But I didn't look at the example yet (rotating gif is not my use case).

Now I understand what you mean. I'll close this PR and I will later open another one with:
- the unused import in the gif example
- a new example which resembles my use case better

Also I think the examples could be put more prominently in readme, maybe I'll add a suggestion in the same PR

**Comment by ladyada** [comment]
awesome, sounds good :)

**Pull request closed without merging**
